### ISSUE TITLE
accept additional string like "white moves"

### ISSUE THREAD

**Issue by Kaligule** [Elucidation/tensorflow_chessbot#24]
It would be great if we could find out whos turn it is. This is often given by a comment or a headline. These often contain a string like "white moves" or "blacks turn"

**Comment by Elucidation** [comment]
That was the original version of this, issues #1 #2 made a few attempts at this, however it turned out to be non-trivial to avoid edge cases, some people suggested the ability to choose themselves #17, it was simpler to implement and after a month seemed to be preferred by the subreddit. 

I'd like to revisit this at some point but will close now as duplicate.
