### ISSUE TITLE
About project status

### ISSUE THREAD

**Issue by gj84** [Elucidation/tensorflow_chessbot#31]
Hi, I was trying to do few test on the project but seems to be not  working (at least for me) with the current version. I have found mixed python2 and 3 code, and another kind of issues on both branches. 
So is there any stable version to test the project? Thanks.

**Comment by Elucidation** [comment]
Hey there, the master branch is a mess, I hadn't touched it too deeply since it's mostly for the ipython notebook links, which I was loathe to break, though I'm reconsidering that now.

I just made some updates to the chessfenbot branch to make it python3 stable, as well as showing how to set up the virtual environment. With this I am currently able to run tensorflow_chessbot.py with python 2 and 3. Let me know if you have any issues running it via this issue.
