### ISSUE TITLE
Docker image fails to run on Mac

### ISSUE THREAD

**Issue by 1int** [Elucidation/tensorflow_chessbot#35]
I've installed docker and followed the instruction to run chessfenbot in it:
docker run -dt --rm --name cfb -v auth_config.py:/tcb/auth_config.py elucidation/tensorflow_chessbot e1754c68589d2a796c6ddcd0c6655de8a9dda98afe28a39cbed5e120360d5646

But all I see is 'currently in /tcb' message, and then it stops.
I've tried :latest and  v1.1.

Macos Sierra 10.12.

**Comment by colwem** [comment]
I guess I get the same thing.  When using the -d flag there's simply no output, not sure why the instructions use that flag. With 

```
docker run -t --rm --name cfb -v auth_config.py:/tcb/auth_config.py elucidation/tensorflow_chessbot ./tensorflow_chessbot.py
```

I get 

```
Traceback (most recent call last):
  File "./tensorflow_chessbot.py", line 43, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'
```

I've tried running this many different ways now with no luck no matter what I do. I would LOVE to get this running as I have a very cool project I would like to use this for.

**Comment by Elucidation** [comment]
@colwem Did you try this over 3 days ago? At some point before that the dockerfile was broken since gcr.io stopped providing a docker image for tensorflow (or moved it).

I changed it 3 days ago to now use tensorflow/tensorflow https://hub.docker.com/r/elucidation/tensorflow_chessbot/~/dockerfile/

For both of you, v1.2 and latest should be working now, this one is what I run and seems to be working for ChessFenBot. The command I use to start the docker instance is

```
docker run -dt --name <instance_name> -v <path-to-praw.ini>:/tcb/praw.ini --restart=on-failure:10 elucidation/tensorflow_chessbot
```

Also, if you don't want to use docker, I updated the readme in the chessfenbot branch to show how to set up a virtual environment to run it

**Comment by colwem** [comment]
@Elucidation Yeah, when I made that comment I had just come back to trying to use this project after trying last week so I missed your updates.  Turns out the local method works now.  Docker though I did try yesterday and it did not work.  So ultimately I'm ok, I have it working so problem solved.

Also, what's the purpose of the -d flag and the -v flag here? -d which it says is "detach" just means I get no output.  So why?  Granted I actually have no idea how to use docker so maybe there's more to this than the command you are given and I'm not doing this correctly.  Your command just exits with no output.  When I append to the end the ./tensorflow_chessbot --filepath etc.... and I remove the -d flag I get the error listed above.

**Comment by Elucidation** [comment]
@colwem https://docs.docker.com/engine/reference/run/#detached--d should answer in detail, but it's mostly for convenience since I'm running them on a cloud instance and want to be able SSH into them, and I want them to automatically restart the docker process if it crashes

**Comment by Elucidation** [comment]
Hopefully the change has fixed the original posters issue, if not feel free to re-open
