### ISSUE TITLE
Use characters to show chessboard instead of fen-to-image.com

### ISSUE THREAD

**Issue by Elucidation** [Elucidation/tensorflow_chessbot#4]
Found this on the [Sunfish](https://github.com/thomasahle/sunfish) readme

```
  8 ♖ ♘ ♗ ♕ ♔ ♗ · ♖
  7 ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
  6 · · · · · ♘ · ·
  5 · · · · · · · ·
  4 · · · · ♟ · · ·
  3 · · · · · · · ·
  2 ♟ ♟ ♟ ♟ · ♟ ♟ ♟
  1 ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
    a b c d e f g h
```

Could potentially draw the notation out in-comment instead of as an image, not sure if encoding is visible to all/majority of /r/chess users. Perhaps also link fen-to-image as a fallback?

Could also do a table

| a | b | c |
| --- | --- | --- |
| ♙ | ♙ | ♙ |
| . |  |  |
| ♜ | ♛ | ♚ |

...

**Comment by dllu** [comment]
A table would be better. The chess unicode characters tend to be slightly wider than usual, even for a monospace font. Even on my computer the example you provided doesn't look right:

![pic](https://pics.dllu.net/file/dllu-sc/TOkPn1G0Zp71pF9l.png)

By the way, I'm working on [an alternative to fen-to-image.com](https://github.com/daniel-lawrence-lu/puppyfen) which is

1. fast, serves a 15 KiB SVG or 25 KiB PNG image for typical chess positions from behind Cloudflare
2. uses familiar set of pieces by CBurnett, also seen on Wikipedia and Lichess
3. isn't full of glitches such as ![image](https://user-images.githubusercontent.com/14482624/50941270-04ef6500-1439-11e9-8c18-6e2d9f9c5ee8.png)

Example: [`https://chess.dllu.net/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png`](https://chess.dllu.net/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png)

![example](https://chess.dllu.net/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png)

Example: [`https://chess.dllu.net/black/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png`](https://chess.dllu.net/black/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png)

![example](https://chess.dllu.net/black/2kr3r/1p1n1ppp/2pR4/5b2/2B1n3/5NB1/PP3PPP/2K4R.png)

**Comment by Elucidation** [comment]
Good point on the table.
How would you be hosting the generator? I'd like the bot to be using something that should be running reasonably consistently for the next few years.
Is there a way to choose the bg color to be different, such as grayscale?

**Comment by dllu** [comment]
It's running on a $5 Linode instance behind a cloudflare free tier.

I can change the colour or you could just fork the project and run your own one (you could run it on the same machine that the bot runs on).

I'm probably going to keep working on puppyfen so it might not be that stable for the next few weeks. I'm planning to add threading, cache purging (so that my VPS doesn't get filled up with PNG images), fen validation (to avoid people spamming the server with bad fens like /qqqqqqqqqqqqqqqqqqqqqqqqqqq...), and maybe new features such as a homepage and adding the coordinates to the chessboard.
